[panels]
# 9 panels
# - What should be in the panel
# - Relative width and height of the panel
# - Seperators
# - Seperator color
# - Title of the panel (default + override)
# - Title color
# - Color of border of panel
# - Other options in: https://fedeclaudi.github.io/Term.jl/stable/ren/panel/